### ISSUE TITLE
Pinata IPFS Not accepting markdowns with HTML Tags

### ISSUE THREAD

**Issue by EdSDR** [renlabs-dev/commune-ts#100]

**Comment by steinerkelvin** [comment]
I guess we can pay $20/month on Pinata.cloud and not even have to change anything in our code and be over with this.

We can then add to our backlog, with (very) low-priority, running our own pinning API.

![image](https://github.com/user-attachments/assets/5bdf45fb-12cf-4d11-bc25-9338682da794)

**Comment by steinerkelvin** [comment]
@Supremesource Can you add Pinata credentials to our Bitwarden org?

**Comment by Supremesource** [comment]
> @Supremesource Can you add Pinata credentials to our Bitwarden org?

yes, will do

**Comment by Supremesource** [comment]
> I guess we can pay $20/month on Pinata.cloud and not even have to change anything in our code and be over with this.
> 
> We can then add to our backlog, with (very) low-priority, running our own pinning API.
> 
> ![image](https://private-user-images.githubusercontent.com/2822370/359622087-5bdf45fb-12cf-4d11-bc25-9338682da794.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxODYxOTQsIm5iZiI6MTcyNDE4NTg5NCwicGF0aCI6Ii8yODIyMzcwLzM1OTYyMjA4Ny01YmRmNDVmYi0xMmNmLTRkMTEtYmMyNS05MzM4NjgyZGE3OTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMjAzMTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzgzNDYzY2IyMTk3MTkyNDI1NGM2MGZkMDlmZDBjNTc0OTQyNzIwNTFhNTU2ZDkzZTYwYTVmZTBjMWVkMWU4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wKIz530IN46wOneNzwTiBvUN7TWcN7Cz4_VHXIKilOI)

oh yeah, we should do that

**Comment by steinerkelvin** [comment]
btw, if you guys can turn the title / name field into a string to set as file name would be good instead of "File to upload" 
@EdSDR @vinicius-sacramento 

https://github.com/agicommies/commune-ts/blob/59ce7594691069c85b080a6182a7262447841c6d/apps/commune-governance/src/app/api/files/route.ts#L19

**Comment by steinerkelvin** [comment]
Error while trying to add the credit card, crap.

![image](https://github.com/user-attachments/assets/c737a8e0-9685-4f4b-8e84-4832841a0662)
