### ISSUE TITLE
Second click on wallet without selecting a account shows the wallet screen

### ISSUE THREAD

**Issue by EdSDR** [renlabs-dev/commune-ts#104]
![Image](https://github.com/user-attachments/assets/ff8c6493-39aa-4c05-a550-5d0e79160301)

**Comment by vinicius-sacramento** [comment]
It have been fixed on the new Wallet dropdown.

https://github.com/user-attachments/assets/d648c79d-8ffe-4478-9d18-9cf6e20a3a04
