### ISSUE TITLE
Wallet Icons Not Loading

### ISSUE THREAD

**Issue by EdSDR** [renlabs-dev/commune-ts#126]
![Image](https://github.com/user-attachments/assets/07095fe3-01a0-4028-aa45-9abd6c082041)

so just open the website i guess

**Comment by vinicius-sacramento** [comment]
How to replicate the problem:

The problem occurs when you open the expanded proposal screen and either reload while on it or enter it through an external link.
This causes the icons to break, and to fix it, you need to go back to the main governance screen and reload again.
