### ISSUE TITLE
Max button on unstake method should fill it with the staked balance of the selected key

### ISSUE THREAD

**Issue by EdSDR** [renlabs-dev/commune-ts#128]
![Image](https://github.com/user-attachments/assets/4375e047-4157-4222-aab4-315bb1950e40)

**Comment by Etandooley** [comment]
@EdSDR Are you having issues with staking?

**Comment by EdSDR** [comment]
> [@EdSDR](https://github.com/EdSDR) Are you having issues with staking?

No, this is more like an extra function to the max button

**Comment by Etandooley** [comment]
Okay
