### ISSUE TITLE
fix wallet behaviors

### ISSUE THREAD

**Issue by vinicius-sacramento** [renlabs-dev/commune-ts#186]
# Wallet Functionality Improvements and New Validations

Following the previous reports, @Supremesource brought these issues to my attention, and I began debugging our wallet. We identified and addressed several problems across different instances and implemented new validations:

![Image](https://github.com/user-attachments/assets/35bc4c97-52ca-489d-b745-bba933d1d1a9)
![Image](https://github.com/user-attachments/assets/fbf1623e-12e6-42ff-900a-172c30161142)

**Comment by vinicius-sacramento** [comment]
## 1. Sending Funds

**Issue:** The "Max" button didn't account for transaction fees when transferring balance to another wallet address.

**Impact:** Users couldn't send their entire balance due to insufficient funds for fees.

**Resolution:** 
- We've adjusted the "Max" calculation to reserve funds for transaction fees, ensuring successful transfers.
- New validations on the amount input and "Start Transaction" button have been implemented:
  - The input is now validated to prevent users from entering amounts exceeding their wallet balance (including fees).
  - The "Start Transaction" button is disabled when the entered amount (plus fees) exceeds the available balance.

## 2. Staking

**Issue:** The "Max" button allowed users to stake their entire free balance.

**Impact:** Transactions failed as a minimum balance (approx. 0.000001) must be maintained in the wallet.

**Resolution:** 
- We've implemented a reserve amount when calculating the maximum stakeable balance.
- New validations have been added:
  - The amount input is now validated to prevent staking more COMAIs than the available free balance.
  - The "Start Transaction" button is disabled when the entered amount exceeds the free balance.

## 3. Unstaking

**Issue:** The "Max" button displayed the free balance instead of the staked amount for a specific validator.

**Impact:** Users encountered errors when attempting to unstake, as free balance is unrelated to staked balance.

**Resolution:** 
- We've corrected the "Max" calculation to show the actual staked amount for each validator.

- New validations have been added for known validators with known stakes:
  - The amount input is validated to prevent unstaking more than the staked amount for the selected validator.
  - The "Start Transaction" button is disabled when the entered amount exceeds the staked amount.
  -  For unlisted validators, we've removed the "Max" button and don't restrict the input amount.
  
## 4. Stake Transfers

**Issue:** The "Max" button considered the user's free balance instead of the staked amount for a specific validator.

**Impact:** Users couldn't accurately transfer their staked amounts between validators.

**Resolution:** 
- We now display a list of staked validators in the "From Validator".
- The "Max" button calculates the correct staked amount for the selected validator.
- For unlisted validators, we've removed the "Max" button and don't restrict the input amount.
- New validations have been added for known validators with known stakes:
  - The amount input is validated to prevent transferring more than the staked amount.
  - The "Start Transaction" button is disabled when the entered amount exceeds the staked amount.

## Additional Notes

- If a user attempts to unstake or transfer stakes without sufficient funds, an error message will be displayed.
- These improvements aim to enhance user experience and prevent unintended transaction failures.
- The new input validations and button disabling mechanisms provide real-time feedback to users, reducing the likelihood of errors.

## Test evidences

### Staking
https://github.com/user-attachments/assets/8cd0b701-779c-4829-a42a-9a73d4feda0c

### Stake Transfers
https://github.com/user-attachments/assets/a9ad0c27-b59a-4edf-bdbe-33ac0cdb4c18

### Unstaking
https://github.com/user-attachments/assets/3d07bcc0-94f8-4620-8935-040fab8e4c13

### Sending funds
https://github.com/user-attachments/assets/fb5147b4-da61-4a8d-a0f3-21de62e93eee

**Comment by EdSDR** [comment]
LGTM
