### ISSUE TITLE
Create "caching" repository for better proposal data consumption 

### ISSUE THREAD

**Issue by EdSDR** [renlabs-dev/commune-ts#41]

**Comment by steinerkelvin** [comment]
caching or crashing?

**Comment by EdSDR** [comment]
@steinerkelvin can you take a look into this? i think the current way we are dealing with `staleTime` is causing this issue where we are refetching the stakeOut in a way that is not necessary and its impacting the performance.

**Comment by EdSDR** [comment]
Assigned @vinicius-sacramento since he is working on front end integration of it
